"""Build the human-verification worksheet for stage-2 screening decisions.

WHY THIS EXISTS. Screening is model-assisted, and a model-assisted screen is
publishable only when a human verifies it. The verification was going to happen
in Rayyan; that is no longer the plan, so the verification artefact has to be the
worksheet itself.

WHAT IT PRODUCES. One Markdown file listing every ADVANCE with its title, year,
journal and the reason it advanced, followed by the EXCLUDE decisions grouped by
reason so a reviewer can scan a whole class at once rather than 1,125 rows one at
a time. Known-positive studies are marked, because a reviewer who sees them
correctly advanced has a calibration check on everything else in the list.

WHAT IT DOES NOT DO. It does not re-decide anything. The log is the record; this
is a view of it.

USAGE
    python scripts/build_screening_worksheet.py
    python scripts/build_screening_worksheet.py --arm A_organism_first
"""
import argparse
import collections
import csv
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
STAGE1 = ROOT / "revision_sistematica" / "cribado" / "screening_stage1.csv"
LOG = ROOT / "revision_sistematica" / "cribado" / "screening_stage2_decisions.csv"
INDEX = ROOT / "quality_reports" / "corpus_identifier_index.txt"

csv.field_size_limit(10_000_000)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--arm", default=None)
    ap.add_argument("--out", default="quality_reports/screening_worksheet.md")
    args = ap.parse_args()

    with open(STAGE1, encoding="utf-8", newline="") as fh:
        pool = {r["pmid"]: r for r in csv.DictReader(fh) if r["stage1"] == "ADVANCE"}

    # last row per pmid wins, so corrections supersede
    decided = {}
    with open(LOG, encoding="utf-8", newline="") as fh:
        for r in csv.DictReader(fh):
            decided[r["pmid"]] = r

    known = {}
    for line in INDEX.read_text(encoding="utf-8").splitlines():
        if line.startswith("pmid:"):
            ident, _, sid = line.partition("\t")
            known[ident.split(":", 1)[1]] = sid.strip()

    rows = [(p, d) for p, d in decided.items() if p in pool]
    if args.arm:
        rows = [(p, d) for p, d in rows if args.arm in (pool[p].get("arms") or "")]

    adv = [(p, d) for p, d in rows if d["verdict"] == "ADVANCE"]
    exc = [(p, d) for p, d in rows if d["verdict"] == "EXCLUDE"]
    adv.sort(key=lambda x: (pool[x[0]]["year"], pool[x[0]]["title"]))

    L = [
        "# Screening worksheet — stage 2 (title)",
        "",
        "Generated by `scripts/build_screening_worksheet.py` from",
        "`revision_sistematica/cribado/screening_stage2_decisions.csv`. This is a **view of the log**, not",
        "a second decision: nothing here re-decides anything.",
        "",
        "**This is the human-verification artefact.** The screen was model-assisted, and",
        "a model-assisted screen is reportable only when a human checks it. Reviewer:",
        "read the ADVANCE list in full, then sample the EXCLUDE classes below.",
        "",
        "| | n |",
        "|---|---|",
        "| decided | %d |" % len(rows),
        "| ADVANCE | **%d** |" % len(adv),
        "| EXCLUDE | %d |" % len(exc),
        "| already in this corpus | %d |" % sum(1 for p, _ in rows if p in known),
        "",
        "## ADVANCE — read every row",
        "",
        "`✔` marks a study already included in this review. Those are the calibration",
        "set: if they are all here, the criteria were applied at least as broadly as",
        "the review's own.",
        "",
        "| | PMID | Year | Title | Journal | Why it advanced |",
        "|---|------|------|-------|---------|-----------------|",
    ]
    for p, d in adv:
        r = pool[p]
        mark = "✔" if p in known else ""
        L.append("| %s | [%s](https://pubmed.ncbi.nlm.nih.gov/%s/) | %s | %s | %s | %s |" % (
            mark, p, p, r["year"],
            (r["title"] or "").replace("|", "/")[:110],
            (r["journal"] or "")[:38],
            (d["reason"] or "")[:95]))

    L += ["", "## EXCLUDE — sample each class", ""]
    by_reason = collections.Counter(d["reason"] for _, d in exc)
    for reason, n in by_reason.most_common():
        L.append("**%d records** — %s" % (n, reason))
        L.append("")
        sample = [(p, pool[p]) for p, d in exc if d["reason"] == reason][:8]
        for p, r in sample:
            L.append("- `%s` %s — %s" % (p, r["year"], (r["title"] or "")[:95]))
        L.append("")

    out = ROOT / args.out
    out.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print("decided %d | ADVANCE %d | EXCLUDE %d | known positives %d"
          % (len(rows), len(adv), len(exc), sum(1 for p, _ in rows if p in known)))
    print("wrote", out)


if __name__ == "__main__":
    main()
