"""Replace the risk-of-bias paragraph in Results with one that describes the
appraisal actually performed.

The paragraph being replaced claimed ratings were "complete for all 31
study-arms", then spent most of its length rating four randomised trials that
the population criterion has since removed from the corpus, and asserted
"Low-to-moderate risk" for the case reports on the strength of a per-domain
tabulation it conceded "was not separately retained". None of that survives
contact with the per-arm appraisal now produced by scripts/R/12_risk_of_bias.R.
"""
import pathlib

BS = chr(92)
root = pathlib.Path(__file__).resolve().parent.parent
p = root / "paper/sections/results.tex"
s = p.read_text(encoding="utf-8")

start = s.find("Risk-of-bias ratings (ROBINS-I")
assert start > 0, "anchor not found"
end = s.find("\n", start)
assert end > start

new = (
    "Risk of bias is appraised for every one of the 31 pooling-eligible arms, and the appraisal is "
    "generated by rule from recorded extraction metadata (" + BS + "texttt{scripts/R/12" + BS + "_risk" + BS +
    "_of" + BS + "_bias.R}) rather than asserted, so it regenerates with the data and can be audited "
    "line by line (" + BS + "Cref{tab:rob-per-arm}). Because the population criterion removed every "
    "randomised trial from the synthesis, a single instrument now applies throughout: the four domains "
    "of " + BS + "textcite{Murad2018_casereports} for case reports and series --- selection, "
    "ascertainment, causality and reporting. We state at the outset what this is and is not. It is a "
    "systematic floor built only on facts the extraction already established, scoring a domain as "
    "unclear wherever the extraction is silent; it is not a substitute for a second reviewer reading "
    "each full text and judging each domain by hand, which this review has not had "
    "(Section~" + BS + "ref{sec:discussion-limitations}).\n\n"

    "The result is worse than the partial assessment this review previously reported. "
    "" + BS + "textbf{All 31 arms rate High risk of bias overall}, and the domain responsible is "
    "causality: 30 of the 31 arms administered phage together with antibiotics, so no arm can attribute "
    "its outcome to the phage rather than to the co-intervention, and Murad's causality domain cannot be "
    "satisfied anywhere in the corpus. The single exception (" + BS + "textcite{Arya2026_pji_natcomms}, "
    "phage monotherapy) rates Moderate on that domain and is one patient. The remaining domains do "
    "discriminate: selection is High in 20 arms, Moderate in 6 and Low in 5; ascertainment is High in 2, "
    "Moderate in 18 and Low in 11; reporting is High in 7, Moderate in 7 and Low in 17.\n\n"

    "One quantity in that profile runs against intuition and is worth reporting. The 20 stand-alone "
    "single-patient reports --- the arms rated High on selection, because publishing one patient is "
    "itself the selection event --- together carry only 20 of the corpus's 82 patients. Three larger "
    "sources (" + BS + "citeauthor{Pirnay2024_natmicrobiol}, " + BS + "citeauthor{Onallah2023_med} and "
    "Chan et al.\\ 2025) carry 56 between them. Since the pooling model weights by patient rather than by "
    "arm, the many case reports contribute a minority of the evidence in every cell: their share of "
    "patients ranges from 10" + BS + "% to 35" + BS + "% and never approaches half. The corpus is "
    "numerically dominated by a few series, which is the opposite of what its design distribution alone "
    "would suggest, and it is why the risk-of-bias downgrade in Section~" + BS + "ref{sec:results-grade} "
    "is keyed to the uniform High overall rating rather than to the case-report share.\n\n"

    "Two consequences follow, and neither favours this review. First, the GRADE risk-of-bias domain is "
    "" + BS + "emph{uniform}: every cell is downgraded two levels, because every cell rests entirely on "
    "High-risk evidence. It therefore carries no information distinguishing one cell from another, and we "
    "report it as uniform rather than tuning a threshold until it appears to discriminate. Second, the "
    "earlier characterisation of the single-patient reports as ``Low-to-moderate risk'' was not supportable: "
    "it rested on a per-domain tabulation that was never retained, and the rule-based appraisal that "
    "replaces it reaches the opposite conclusion. These ratings feed the GRADE assessment in "
    "Section~" + BS + "ref{sec:results-grade}."
)

s = s[:start] + new + s[end:]
p.write_text(s, encoding="utf-8", newline="\n")
print("risk-of-bias paragraph rewritten (" + str(len(new)) + " chars)")
