"""Pull what the eligibility decision actually turns on, for the registry candidates.

WHY THIS EXISTS. Twelve ClinicalTrials.gov records name Pseudomonas and are not in
this corpus. Deciding them from the brief title would repeat the mistake that put
Law 2019 outside this review for two rounds -- it was set aside as a presumed
conference abstract on a guess about its title and turned out to be a full report
of a distinct patient.

The decision turns on three things a title never shows:

  1. Does the ELIGIBILITY CRITERIA text require resistance at entry? This review
     excludes trials whose protocol admits patients on infection or colonisation
     alone, because the population demonstrably was not selected for resistance
     and pooling it would place possibly-susceptible patients inside a review of
     resistant infection. That rule already removed PhagoBurn, BX004-A,
     SWARM-P.a./AP-PA02 and CYPHY, and it must be applied here identically.

  2. Are there POSTED RESULTS? A protocol registration with no results carries no
     outcome data to extract, whatever its design.

  3. Is the P. aeruginosa arm SEPARABLE? A multi-pathogen trial reporting pooled
     outcomes cannot contribute, which is the mixed-not-separable rule.

This fetches all three per record. It does not decide -- it assembles what the
decision needs, and the adjudication is recorded separately with a reason each.

USAGE
    python scripts/screen_clinicaltrials_candidates.py
"""
import csv
import json
import pathlib
import re
import time
import urllib.parse
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "raw" / "clinicaltrials_gov.csv"
INDEX = ROOT / "quality_reports" / "corpus_identifier_index.txt"
OUT = ROOT / "quality_reports" / "clinicaltrials_candidate_screen.md"
API = "https://clinicaltrials.gov/api/v2/studies/"

RESIST = re.compile(
    r"multi[- ]?drug[- ]?resistan|multidrug|\bMDR\b|extensively drug[- ]?resistan|\bXDR\b|"
    r"pan[- ]?drug[- ]?resistan|\bPDR\b|difficult[- ]to[- ]treat|\bDTR\b|"
    r"resistan\w*\s+(?:to|strain|isolate|organism)|carbapenem[- ]resistan|"
    r"antibiotic[- ]resistan|refractory to (?:antibiotic|antimicrobial)", re.I)


def dig(d, path):
    cur = d
    for p in path.split("."):
        cur = cur.get(p) if isinstance(cur, dict) else None
        if cur is None:
            return None
    return cur


def main():
    with open(SRC, encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    in_corpus = {l.split("\t")[0].split(":", 1)[1].upper()
                 for l in INDEX.read_text(encoding="utf-8").splitlines()
                 if l.startswith("nct:")}

    def mentions_pa(r):
        blob = r["conditions"] + " " + r["interventions"] + " " + r["briefTitle"]
        return re.search(r"pseudomonas|aeruginosa", blob, re.I) is not None

    cands = sorted([r for r in rows if mentions_pa(r) and r["nct_id"] not in in_corpus],
                   key=lambda x: x["nct_id"])
    print("candidates to assess:", len(cands), "\n")

    lines = [
        "# ClinicalTrials.gov candidates — what the eligibility decision turns on",
        "",
        "Generated by `scripts/screen_clinicaltrials_candidates.py` on 2026-08-03.",
        "",
        "Twelve registry records name *Pseudomonas* and are not in this corpus. For",
        "each, three things the brief title does not show: whether the protocol",
        "**required resistance at entry**, whether **results are posted**, and whether",
        "the *P. aeruginosa* arm is **separable**. The population rule that excluded",
        "PhagoBurn, BX004-A, SWARM-P.a./AP-PA02 and CYPHY applies here identically.",
        "",
    ]

    for r in cands:
        nct = r["nct_id"]
        time.sleep(0.35)
        url = API + nct + "?format=json"
        with urllib.request.urlopen(url, timeout=90) as fh:
            d = json.load(fh)

        elig = dig(d, "protocolSection.eligibilityModule.eligibilityCriteria") or ""
        brief = dig(d, "protocolSection.descriptionModule.briefSummary") or ""
        has_results = bool(d.get("resultsSection"))
        conds = "; ".join(dig(d, "protocolSection.conditionsModule.conditions") or [])
        status = dig(d, "protocolSection.statusModule.overallStatus") or ""
        stype = dig(d, "protocolSection.designModule.studyType") or ""
        enrol = dig(d, "protocolSection.designModule.enrollmentInfo.count")
        sponsor = dig(d, "protocolSection.sponsorCollaboratorsModule.leadSponsor.name") or ""

        hits = sorted({m.group(0).lower() for m in RESIST.finditer(elig)})
        hits_brief = sorted({m.group(0).lower() for m in RESIST.finditer(brief)})
        multi = len([c for c in (dig(d, "protocolSection.conditionsModule.conditions") or [])
                     if not re.search(r"pseudomonas|aeruginosa", c, re.I)])

        print("%-12s results=%-3s resist-in-eligibility=%-3s other-conditions=%d"
              % (nct, "yes" if has_results else "no",
                 "yes" if hits else "no", multi))

        lines += [
            "## %s — %s" % (nct, r["briefTitle"]),
            "",
            "- **Sponsor:** %s" % sponsor,
            "- **Status / type / enrolment:** %s · %s · %s" % (status, stype, enrol or "not stated"),
            "- **Conditions:** %s" % (conds or "*none registered*"),
            "- **Results posted:** %s" % ("**yes**" if has_results else "no"),
            "- **Resistance required at entry:** %s" % (
                "**yes** — matched: `%s`" % "`, `".join(hits) if hits else
                "**no match in the eligibility criteria**"),
            "- **Resistance mentioned in the summary:** %s" % (
                "`%s`" % "`, `".join(hits_brief) if hits_brief else "no"),
            "- **Non-*Pseudomonas* conditions also registered:** %d" % multi,
            "",
            "<details><summary>Eligibility criteria (verbatim)</summary>",
            "",
            "```",
            (elig.strip()[:2200] or "(none registered)"),
            "```",
            "",
            "</details>",
            "",
        ]

    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("\nwrote", OUT)


if __name__ == "__main__":
    main()
